server.port=8083
spring.application.name=flight-service

spring.datasource.url=${FLIGHT_DB_URL:jdbc:postgresql://localhost:5434/airport_ops_db?currentSchema=flight}
spring.datasource.username=${FLIGHT_DB_USERNAME:airport_user}
spring.datasource.password=${FLIGHT_DB_PASSWORD:strong-pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=flight

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=flight
spring.flyway.default-schema=flight
spring.flyway.create-schemas=false
spring.flyway.table=flyway_schema_history

management.endpoints.web.exposure.include=health,info

app.iam.jwks-uri=${IAM_JWKS_URI:http://127.0.0.1:8081/.well-known/jwks.json}
app.iam.issuer=${IAM_TOKEN_ISSUER:airport-ops-iam}
app.iam.audience=${IAM_TOKEN_AUDIENCE:flight-service}

app.airport-service.base-url=${AIRPORT_SERVICE_BASE_URL:http://127.0.0.1:8082}
