server.port=8082
spring.application.name=airport-service

spring.datasource.url=${AIRPORT_DB_URL:jdbc:postgresql://localhost:5434/airport_ops_db?currentSchema=airport}
spring.datasource.username=${AIRPORT_DB_USERNAME:airport_user}
spring.datasource.password=${AIRPORT_DB_PASSWORD:strong-pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=airport

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=airport
spring.flyway.default-schema=airport
spring.flyway.create-schemas=false
spring.flyway.table=flyway_schema_history

management.endpoints.web.exposure.include=health,info

app.iam.jwks-uri=${IAM_JWKS_URI:http://127.0.0.1:8081/.well-known/jwks.json}
app.iam.issuer=${IAM_TOKEN_ISSUER:airport-ops-iam}
app.iam.audience=${IAM_TOKEN_AUDIENCE:airport-service}
