server.port=8081
spring.application.name=iam-service

spring.datasource.url=${IAM_DB_URL:jdbc:postgresql://localhost:5434/airport_ops_db?currentSchema=iam}
spring.datasource.username=${IAM_DB_USERNAME:airport_user}
spring.datasource.password=${IAM_DB_PASSWORD:strong-pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=iam

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=iam
spring.flyway.default-schema=iam
spring.flyway.create-schemas=false
spring.flyway.table=flyway_schema_history

management.endpoints.web.exposure.include=health,info

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8085/realms/airport-ops
