server.port=8081
spring.application.name=iam-service

spring.datasource.url=${IAM_DB_URL:jdbc:postgresql://localhost:5434/airport_ops_db?currentSchema=iam}
spring.datasource.username=${IAM_DB_USERNAME:airport_user}
spring.datasource.password=${IAM_DB_PASSWORD:strong-pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=iam

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=iam
spring.flyway.default-schema=iam
spring.flyway.create-schemas=false
spring.flyway.table=flyway_schema_history

management.endpoints.web.exposure.include=health,info

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8085/realms/airport-ops

keycloak.admin.server-url=${KEYCLOAK_ADMIN_SERVER_URL:http://127.0.0.1:8085}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:airport-ops}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:iam-service-admin}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:iam-service-admin-local-secret}

keycloak.session.server-url=${KEYCLOAK_SESSION_SERVER_URL:http://127.0.0.1:8085}
keycloak.session.realm=${KEYCLOAK_SESSION_REALM:airport-ops}
keycloak.session.client-id=${KEYCLOAK_SESSION_CLIENT_ID:iam-service-session}
keycloak.session.client-secret=${KEYCLOAK_SESSION_CLIENT_SECRET:iam-service-session-local-secret}

auth.session.cookie.access-name=airport_ops_access_token
auth.session.cookie.refresh-name=airport_ops_refresh_token
auth.session.cookie.same-site=Lax
auth.session.cookie.secure=${AUTH_SESSION_COOKIE_SECURE:false}

app.aws.region=${AWS_REGION:eu-central-1}
app.mail.from=${APP_MAIL_FROM:}
app.invitation.accept-base-url=${APP_INVITATION_ACCEPT_BASE_URL:http://127.0.0.1:5173/invitations/accept}
app.invitation.dev-link-enabled=${APP_INVITATION_DEV_LINK_ENABLED:true}
app.mfa.encryption-key=${APP_TOTP_ENCRYPTION_KEY:}
app.iam-token.private-key=${IAM_TOKEN_PRIVATE_KEY:}
app.iam-token.private-key-path=${IAM_TOKEN_PRIVATE_KEY_PATH:./iam-token-private-key.txt}
app.iam-token.key-id=${IAM_TOKEN_KEY_ID:iam-key-1}
app.iam-token.ttl-seconds=${IAM_TOKEN_TTL_SECONDS:900}
app.airport-service.base-url=${AIRPORT_SERVICE_BASE_URL:http://127.0.0.1:8082}
